# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 848376b10c901419f53cf7a42e9f94f874928449b50c469422921e2c10167c7b5a37cf23fb277520d5445359dcb375e9e74b280dbd492366e7d6c78696779714

test:
  secret_key_base: 50bd68659098febb18900f36faad3c287f2be2ac5a65dd78b60605dd9d5c4cb7fe3e2db030b769099a0792e858962c8a3eb65ee9cbf13af746c5877452b1b8e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
